// <auto-generated/>
namespace Content.Constants.UI.Layers
{
	public static class LayerType
	{
		public const string POPUPS = "Popups";
		public const string SCREENS = "Screens";
		public const string WINDOWS = "Windows";
	}
}