// <auto-generated/>
namespace Content.Constants.Game.Logic.Inventory
{
	public static class ItemType
	{
		// Currency
		public const string CURRENCY_HARD = "Currency/Hard";
		public const string CURRENCY_SOFT = "Currency/Soft";
		
		// Currency -> Temporary
		public const string CURRENCY_TEMPORARY_ADS_TICKET = "Currency/Temporary/AdsTicket";
	}
}