// <auto-generated/>
namespace Content.Constants.UI.Tabs
{
	public static class TabType
	{
		public const string LEVEL_MAP = "LevelMap";
		public const string SPELLS = "Spells";
		public const string SQUAD = "Squad";
		public const string STATISTICS_RESOURCES = "StatisticsResources";
		public const string STATISTICS_SPELLS = "StatisticsSpells";
		public const string STATISTICS_SQUAD = "StatisticsSquad";
	}
}