// <auto-generated/>
namespace Content.Constants.UI.Windows
{
	public static class WindowType
	{
		public const string AUTHORIZATION = "Authorization";
		public const string CHARACTER_INFO = "CharacterInfo";
		public const string DAILY_REWARD = "DailyReward";
		public const string EXAMPLE = "Example";
		public const string LEVEL = "Level";
		public const string SETTINGS = "Settings";
		public const string SPELL = "Spell";
		public const string STATISTICS = "Statistics";
		
		// Core
		public const string CORE_DEFEAT = "Core/Defeat";
		public const string CORE_LEVEL_UP = "Core/LevelUp";
		public const string CORE_PAUSE = "Core/Pause";
		public const string CORE_VICTORY = "Core/Victory";
		
		// Core -> Lobby
		public const string CORE_LOBBY_SCOREBOARD = "Core/Lobby/Scoreboard";
		public const string CORE_LOBBY_SHOP = "Core/Lobby/Shop";
	}
}