// <auto-generated/>
namespace Content.Constants.UI.Screens
{
	public static class ScreenType
	{
		public const string EXAMPLE = "Example";
		public const string HUD = "HUD";
		public const string LOADING = "Loading";
		public const string LOBBY = "Lobby";
		public const string MAIN_MENU = "MainMenu";
	}
}