// <auto-generated/>
namespace Content.Constants.Audio
{
	public static class AudioEventType
	{
		// Effects
		public const string EFFECTS_DEFEAT = "Effects/Defeat";
		public const string EFFECTS_VICTORY = "Effects/Victory";
		
		// Music
		public const string MUSIC_MAIN_MENU = "Music/MainMenu";
		
		// Music -> Location
		public const string MUSIC_LOCATION_ANCIENT_CITY = "Music/Location/AncientCity";
		public const string MUSIC_LOCATION_DARK_CRYPT = "Music/Location/DarkCrypt";
		public const string MUSIC_LOCATION_DEFAULT = "Music/Location/Default";
		public const string MUSIC_LOCATION_DESERT_WIND = "Music/Location/DesertWind";
		public const string MUSIC_LOCATION_HELL_KITCHEN = "Music/Location/HellKitchen";
		public const string MUSIC_LOCATION_MUSHROOM_MEADOW = "Music/Location/MushroomMeadow";
		public const string MUSIC_LOCATION_THE_ICE_KINGDOM = "Music/Location/TheIceKingdom";
		
		// UI
		public const string UI_CLICK = "UI/Click";
		
		// UI -> MainMenu -> Navigation
		public const string UI_MAIN_MENU_NAVIGATION_CLICK = "UI/MainMenu/Navigation/Click";
		
		// UI -> Window
		public const string UI_WINDOW_CLOSE = "UI/Window/Close";
		public const string UI_WINDOW_OPEN = "UI/Window/Open";
	}
}